//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityUrunTakipSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductTable()
        {
            this.SaleTable = new HashSet<SaleTable>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string Brand { get; set; }
        public Nullable<short> Stock { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> State { get; set; }
        public Nullable<int> Category { get; set; }
    
        public virtual CategoryTable CategoryTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleTable> SaleTable { get; set; }
    }
}
